### ISSUE TITLE
Set direction for user research 

### ISSUE THREAD

**Issue by RyanSibley** [usdoj/foia.gov#27]
We need to decide: 

- Who we're going to talk to

- What we're going to show them

- What questions we're going to ask

To accomplish these things we'll 

- [ ] have a direction setting activity with the team (https://github.com/18F/foia/issues/28)

- [ ] Conduct recruiting for user sessions (https://github.com/18F/foia/issues/29)

- [ ] Create or decide on a prototype to show people (https://github.com/18F/foia/issues/30)

The steps listed above are written out with the end-user for the portal in mind, but could also apply to things we'll do to create a plan for testing with users of A gui.
